### ISSUE TITLE
Data Movement issue

### ISSUE THREAD

**Issue by akashban** [radical-cybertools/radical.entk#581]
Hi @andre-merzky and @lee212 , 

I am facing a general data movement issue between ENTK stages. I replicated the issue with one of the examples in the radical.entk repo: poe.py. 
I have attached the log files here.

I believe the copy_input_data feature is not working: hence data staging in any of the stages/tasks is not happening. If you see the sandbox_remote folder, you will notice that only the first task folder (task.0000) has some files, but the remaining task folders are empty. 
[Logs.zip](https://github.com/radical-cybertools/radical.entk/files/6657428/Logs.zip)

Thank you. 

Kind regards,
Akash

**Comment by akashban** [comment]
Hi @andre-merzky and @lee212 , 

Just wanted to follow up on the above. Thanks

**Comment by andre-merzky** [comment]
Hi @akashban - thanks for the ping, and apologies for the delayed response!  We'll discuss this on our next call and will come back with a time estimate for a fix ASAP.

**Comment by lee212** [comment]
Hi @akashban , 

Thanks for reporting this, you're correct, I can replicate the issue and it was due to incorrect entity to locate files. It would work if you use `instance.uid` instead. for example, change instance of pipeline/stage/task`.name` to `.uid`. FYI, I updated the script here: https://github.com/radical-cybertools/radical.entk/blob/fix/issue_581/examples/simple/poe.py

While you run the script with `uid`, I will check why `name` is broken to locate files, and apply a fix asap.

**Comment by akashban** [comment]
Thank you @lee212 and @andre-merzky for your help. I will come back to you guys after I test the above solution.

**Comment by akashban** [comment]
Hi @andre-merzky and @lee212 , 

The uid fix works. However, I am still facing a data movement issue for my entk script : link_input_data creates broken symlinks. 
I have attached the remote and local sandboxes. I am not able to upload the broken symlink. It is there in remote sandbox/pilot.0001/task.0001. In summary, the first task, i.e., task.0000 works properly. However, the following tasks (say task.0001) that are dependent on the output files of task.0000 does not work due to the link_input_data issue. 

I tried using copy_input_data: that creates no files. 

I tried using download_input_data and then upload_input_data: that also didn't work. 

Please let me know how I can fix this. 
[PACE_logs.zip](https://github.com/radical-cybertools/radical.entk/files/6704622/PACE_logs.zip)

**Comment by lee212** [comment]
@akashban , can you share your entk script? I need to see what went wrong based on your code with the `link_input_data`.

**Comment by akashban** [comment]
Hi @lee212 , we discussed this with our PI: would it be okay with you if we make you a collaborator on our github repo. This way we can share our unpublished codes/entk scripts with you. I would just need your email ID, and our PI can add you to the repo. We sincerely appreciate your help on this matter.

**Comment by lee212** [comment]
@akashban , I will be more than glad to become a collaborator in your repo and check the code from there, lee212 is my github id and hroe.lee@gmail.com. Thank you.

**Comment by akashban** [comment]
@lee212 thank you so much for your offer. I will forward the details to my PI. Once you accept the invitation, I will open a ticket on our repo, and we can continue our conversation there.

**Comment by mturilli** [comment]
@lee212 please report back to this ticket once the issue has been discussed and solved in the private repo of @akashban so that we can track and close this ticket.

**Comment by lee212** [comment]
@mturilli , I checked out the code, and the issue is that the `link_input_data` still uses `name` to locate files instead of `uid` which we verified working/fixing the current error. I asked @akashban to replace `name` with `uid` in the code, in the meantime I will seek if we can use `name` as well.

**Comment by mturilli** [comment]
@lee212 I see https://github.com/radical-cybertools/radical.entk/commit/7ac03b4f951afb44cd67ed668aa0d99350d1247d . Is that ready for a PR? We are about the release EnTK (the usual monthly release) and it would be important to know whether that commit needs to go into the release.

**Comment by andre-merzky** [comment]
> @lee212 I see [7ac03b4](https://github.com/radical-cybertools/radical.entk/commit/7ac03b4f951afb44cd67ed668aa0d99350d1247d) . Is that ready for a PR? We are about the release EnTK (the usual monthly release) and it would be important to know whether that commit needs to go into the release.

@lee212 : quick question, loosely related: the branch `fix/issue_581` seems also be ready - or is that still work in progress?  If not, do you plan to open a PR?

**Comment by lee212** [comment]
Srinivas Mushnoori still wants to use `.name` because of the complexity of the existing code to change, so my responsibility is to check if `.name` is applicable before the release. and yes for the question to merge the branch. I will open a PR so that it can go into the next release.

**Comment by SrinivasMushnoori** [comment]
So @akashban has brought to my attention that the "fix" in `fix/issue_581` is changing `.name` to `.uid` in the examples? 
Please forgive me if I misunderstand, how would this fix any backend issues that are preventing data staging with `.name` ?

Or is this still being worked upon?

**Comment by lee212** [comment]
@SrinivasMushnoori, the issue you're referring to will have to go into a separate branch. This issue (#581) started with `poe.py` example at the beginning and the branch `fix/issue_581` is to address it.

**Comment by lee212** [comment]
@akashban confirmed the branch works, we may merge the PR.
